### ISSUE TITLE
Number of splits should be 4 in example

### ISSUE THREAD

**Issue by Bourhano** [x-datascience-datacamp/2021-assignment-sklearn#82]
Here is the code snippet containing the example:

https://github.com/x-datascience-datacamp/2021-assignment-sklearn/blob/04e7c9670f5a357cdb26f6031f2eaf4e783d94ef/sklearn_questions.py#L26-L27

**Comment by agramfort** [comment]
True. Can you send a PR to fix ? Thanks

**Comment by Bourhano** [comment]
Sure. I sent a PR with the initial state (where the functions were not implemented) fixing just the example. Here is the PR https://github.com/x-datascience-datacamp/2021-assignment-sklearn/pull/83
